base_url = "https://sidoshi.com"

title = "Siddharth Doshi"
author = "Siddharth Doshi"
description = "Siddharth Doshi's personal website and blog"

generate_feeds = true
generate_sitemap = true
generate_robots_txt = true
compile_sass = true
minify_html = true

taxonomies = [{ name = "tags", feed = true }]

[markdown]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false
github_alerts = true
insert_anchor_links = "right"

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
